# Generated by Django 5.0.6 on 2024-05-26 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrateur",
            fields=[
                ("id_admin", models.AutoField(primary_key=True, serialize=False)),
                ("Nom_admin", models.CharField(max_length=20)),
                ("Email_admin", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id_postion",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id_client", models.AutoField(primary_key=True, serialize=False)),
                ("Contact_client", models.CharField(max_length=20)),
                ("Nom_client", models.CharField(max_length=50)),
                ("Email_client", models.EmailField(max_length=254, unique=True)),
                ("Password_client", models.CharField(max_length=20)),
                (
                    "administrateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EasyLiveApp.administrateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appareil",
            fields=[
                ("id_appareil", models.AutoField(primary_key=True, serialize=False)),
                ("Nom_appareil", models.CharField(max_length=120)),
                ("Description", models.TextField()),
                ("etat", models.BooleanField()),
                (
                    "administrateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EasyLiveApp.administrateur",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="EasyLiveApp.client",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="EasyLiveApp.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="control",
            fields=[
                (
                    "id_c",
                    models.CharField(max_length=123, primary_key=True, serialize=False),
                ),
                (
                    "appareil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="EasyLiveApp.appareil",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="EasyLiveApp.client",
                    ),
                ),
            ],
        ),
    ]
