# Generated by Django 5.0.6 on 2024-05-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EasyLiveApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appareil",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="EasyLiveApp.client",
            ),
        ),
        migrations.AlterField(
            model_name="appareil",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="EasyLiveApp.position",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="administrateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="EasyLiveApp.administrateur",
            ),
        ),
        migrations.AlterField(
            model_name="control",
            name="appareil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="EasyLiveApp.appareil",
            ),
        ),
        migrations.AlterField(
            model_name="control",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="EasyLiveApp.client",
            ),
        ),
    ]
