# Generated by Django 5.0.6 on 2024-06-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EasyLiveApp", "0002_alter_appareil_client_alter_appareil_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=20)),
                ("postion", models.CharField(blank=True, max_length=70)),
                ("state", models.IntegerField(blank=True)),
                ("status", models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
